services:
  postgres:
    container_name: install-postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: eighty4
      POSTGRES_USER: eighty4
      POSTGRES_PASSWORD: eighty4
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
