name: e2e

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
#    services:
#      postgres:
#        image: postgres:16
#        ports:
#          - 5432:5432
#        env:
#          POSTGRES_DB: eighty4
#          POSTGRES_USER: eighty4
#          POSTGRES_PASSWORD: eighty4
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 5s
#          --health-timeout 5s
#          --health-retries 10
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
#    - name: sql
#      run: |
#        sudo apt-get install -y postgresql-client
#        PGPASSWORD=eighty4 psql -h localhost -U eighty4 -f v001-init-schema.sql eighty4
#      working-directory: sql
      - run: pnpm i
      - name: typecheck frontend
        run: pnpm exec tsc --build
        working-directory: frontend
      - name: typecheck offline
        run: pnpm exec tsc --build
        working-directory: offline
      - name: playwright
        env:
          CI: true
        run: |
          pnpm exec playwright install --with-deps
          pnpm exec playwright test
        working-directory: e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 30
