name: "Publish: lambdas"

on:
  workflow_call:
    inputs:
      release_id:
        required: true
        type: string
      tag_name:
        required: true
        type: string
      upload_hostname:
        required: true
        type: string

jobs:

  publish-lambdas:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: lambdas
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag_name }}
      - name: Install l3
        run: |
          mkdir -p $HOME/.local/bin
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          RELEASE_URL="https://api.github.com/repos/eighty4/l3/releases/latest"
          ASSET_URL=$(curl -s "$RELEASE_URL" | jq -r '.assets[] | select(.name == "l3-linux-x86_64") | .url')
          curl -H "Accept: application/octet-stream" -Ls $ASSET_URL > "$HOME/.local/bin/l3"
          chmod +x "$HOME/.local/bin/l3"
          l3 -h
      - run: mkdir -p .l3/build/release
      - name: l3 build
        run: l3 build --all --release
      - name: zip lambdas.zip
        run: zip lambdas.zip l3_build.json *.zip
        working-directory: lambdas/.l3/build/release
      - name: upload
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_ID: ${{ inputs.release_id }}
          UPLOAD_HOSTNAME: ${{ inputs.upload_hostname }}
        run: |
          FILE=.l3/build/release/lambdas.zip
          curl --fail --silent -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: $(file $FILE -b --mime-type)" \
            https://$UPLOAD_HOSTNAME/repos/eighty4/install.sh/releases/$RELEASE_ID/assets?name=lambdas.zip \
            --data-binary "@$FILE"
