name: Deploy frontend

on:
  workflow_dispatch:

#permissions:
#  contents: read
#  pages: write
#  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
#    environment:
#      name: github-pages
#      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check env vars
        run: |
          if [ -z "$GH_OAUTH_CLIENT_ID" ]; then exit 1; fi
        env:
          GH_OAUTH_CLIENT_ID: ${{secrets.GH_OAUTH_CLIENT_ID}}
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build
        run: |
          corepack enable && corepack prepare pnpm@latest --activate
          pnpm i
          pnpm build
        env:
          VITE_INSTALL_API_BASE_URL: ${{secrets.EIGHTY4_INSTALL_API_BASE_URL}}
          VITE_GITHUB_CLIENT_ID: ${{secrets.GH_OAUTH_CLIENT_ID}}
        working-directory: frontend
#      - name: Setup Pages
#        uses: actions/configure-pages@v4
#      - name: Upload artifact
#        uses: actions/upload-pages-artifact@v3
#        with:
#          path: 'frontend/dist'
      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: S3 Upload
        run: aws s3 cp dist.zip ${AWS_AMPLIFY_S3_SOURCE}
        env:
          AWS_AMPLIFY_S3_SOURCE: ${{ secrets.AWS_AMPLIFY_S3_SOURCE }}
        working-directory: frontend
      - name: Amplify Deploy
        run: aws amplify start-deployment --app-id ${AWS_AMPLIFY_APP_ID} --branch-name ${AWS_AMPLIFY_BRANCH_NAME} --source-url ${AWS_AMPLIFY_S3_SOURCE}
        env:
          AWS_AMPLIFY_BRANCH_NAME: ${{ secrets.AWS_AMPLIFY_BRANCH_NAME }}
          AWS_AMPLIFY_APP_ID: ${{ secrets.AWS_AMPLIFY_APP_ID }}
          AWS_AMPLIFY_S3_SOURCE: ${{ secrets.AWS_AMPLIFY_S3_SOURCE }}
        working-directory: frontend
#      - name: Deploy to GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v4
